name: 'Test'

on:
  - pull_request
  - push

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Run Lint
        run: npm run lint
      - name: Run TS checks
        run: npm run ts:check
env:
  CI: true
