name: 'Test'

on:
  - pull_request
  - push

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      fail-fast: false
    steps:
      - name: Install modules
        run: npm i
      - name: Check Formatting
        run: npm run prettier
      - name: Run Lint
        run: npm run lint
env:
  CI: true
