name: 'Test'

on:
  - pull_request
  - push

jobs:
  test:
    name: CI
    timeout-minutes: 90
    strategy:
      fail-fast: false
    steps:
      - name: Install modules
        run: npm ci
      - name: Check Formatting
        run: npm run prettier
        if: matrix.command == 'lint'
      - name: Run Lint
        run: npm run lint
        if: matrix.command == 'lint'
